### ISSUE TITLE
编译报错，如何解决

### ISSUE THREAD

**Issue by PPPPPPan** [zebra-ui/zebra-uniapp-swiper#7]
in ./node_modules/@zebra-ui/swiper/libs/update/updateSlides.js

Module parse failed: Identifier 'key' has already been declared (223:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|               // #endif
|               // #ifndef MP-BAIDU
>               const key = swiper.isHorizontal() && rtl ? 'margin-left' : getDirectionLabel('margin-right');
|               // #endif
|               slides.filter((_, slideIndex) => {

**Comment by lp20010415** [comment]
`
// vue.config.js
module.exports = {
    transpileDependencies:['@zebra-ui/swiper']
}
`
